//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.artech.com/", ConfigurationName="ServiceReference1.CalculatorService")]
    public interface CalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/ADD", ReplyAction="http://www.artech.com/CalculatorService/ADDResponse")]
        int ADD(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/ADD", ReplyAction="http://www.artech.com/CalculatorService/ADDResponse")]
        System.Threading.Tasks.Task<int> ADDAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/GetUsers", ReplyAction="http://www.artech.com/CalculatorService/GetUsersResponse")]
        System.Data.DataSet GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/GetUsers", ReplyAction="http://www.artech.com/CalculatorService/GetUsersResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/GetUserInfoById", ReplyAction="http://www.artech.com/CalculatorService/GetUserInfoByIdResponse")]
        System.Data.DataSet GetUserInfoById(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/GetUserInfoById", ReplyAction="http://www.artech.com/CalculatorService/GetUserInfoByIdResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserInfoByIdAsync(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/SaveUser", ReplyAction="http://www.artech.com/CalculatorService/SaveUserResponse")]
        bool SaveUser(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/SaveUser", ReplyAction="http://www.artech.com/CalculatorService/SaveUserResponse")]
        System.Threading.Tasks.Task<bool> SaveUserAsync(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/DeleteUser", ReplyAction="http://www.artech.com/CalculatorService/DeleteUserResponse")]
        bool DeleteUser(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/DeleteUser", ReplyAction="http://www.artech.com/CalculatorService/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/UpdateUser", ReplyAction="http://www.artech.com/CalculatorService/UpdateUserResponse")]
        bool UpdateUser(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/UpdateUser", ReplyAction="http://www.artech.com/CalculatorService/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/ByUserPwdAndUserName", ReplyAction="http://www.artech.com/CalculatorService/ByUserPwdAndUserNameResponse")]
        System.Data.DataSet ByUserPwdAndUserName(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/ByUserPwdAndUserName", ReplyAction="http://www.artech.com/CalculatorService/ByUserPwdAndUserNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ByUserPwdAndUserNameAsync(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/ByUserNameUser", ReplyAction="http://www.artech.com/CalculatorService/ByUserNameUserResponse")]
        System.Data.DataSet ByUserNameUser(Entity.EntityAdmin entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.artech.com/CalculatorService/ByUserNameUser", ReplyAction="http://www.artech.com/CalculatorService/ByUserNameUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ByUserNameUserAsync(Entity.EntityAdmin entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorServiceChannel : Client.ServiceReference1.CalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.CalculatorService>, Client.ServiceReference1.CalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ADD(int a, int b) {
            return base.Channel.ADD(a, b);
        }
        
        public System.Threading.Tasks.Task<int> ADDAsync(int a, int b) {
            return base.Channel.ADDAsync(a, b);
        }
        
        public System.Data.DataSet GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public System.Data.DataSet GetUserInfoById(Entity.EntityAdmin entity) {
            return base.Channel.GetUserInfoById(entity);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserInfoByIdAsync(Entity.EntityAdmin entity) {
            return base.Channel.GetUserInfoByIdAsync(entity);
        }
        
        public bool SaveUser(Entity.EntityAdmin entity) {
            return base.Channel.SaveUser(entity);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUserAsync(Entity.EntityAdmin entity) {
            return base.Channel.SaveUserAsync(entity);
        }
        
        public bool DeleteUser(Entity.EntityAdmin entity) {
            return base.Channel.DeleteUser(entity);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(Entity.EntityAdmin entity) {
            return base.Channel.DeleteUserAsync(entity);
        }
        
        public bool UpdateUser(Entity.EntityAdmin entity) {
            return base.Channel.UpdateUser(entity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(Entity.EntityAdmin entity) {
            return base.Channel.UpdateUserAsync(entity);
        }
        
        public System.Data.DataSet ByUserPwdAndUserName(Entity.EntityAdmin entity) {
            return base.Channel.ByUserPwdAndUserName(entity);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ByUserPwdAndUserNameAsync(Entity.EntityAdmin entity) {
            return base.Channel.ByUserPwdAndUserNameAsync(entity);
        }
        
        public System.Data.DataSet ByUserNameUser(Entity.EntityAdmin entity) {
            return base.Channel.ByUserNameUser(entity);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ByUserNameUserAsync(Entity.EntityAdmin entity) {
            return base.Channel.ByUserNameUserAsync(entity);
        }
    }
}
